- hosts: all
  vars:
    packages:
      - apache2
      - tree
      - unzip
  become: yes
  tasks:
  - name: Install Apache
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes